# This workflow will do a clean install of node dependencies and run tests and
# validations. This will use the pinned version inside the .nvmrc file
# for the node installation.
#
# Required secrets:
# ------------------------------------------------------------------------------
# (none)

name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests and validations
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: make tests

      - name: Run coverage report
        uses: codecov/codecov-action@v4

      - name: Run validations
        run: make validate
